### ISSUE TITLE
Build agents get stuck in stopping state when it reaches idle timeout

### ISSUE THREAD

**Issue by redmoses** [yandex-qatools/teamcity-openstack-plugin#40] opened 2019-09-04 04:47 UTC
When we configure `Terminate instance idle time` in a cloud profile, agents get stuck in stopping state intermittently when idle time is reached. We see something like below in the UI -

![Screen Shot 2019-09-04 at 11 35 22 AM](https://user-images.githubusercontent.com/4059490/64226118-4b358f00-cf08-11e9-8f06-8444d895399f.png)

From our investigations we think that this problem occurs mostly when Teamcity is trying to stop multiple agents which reached idle time limit. We also see that these agents actually are removed from Openstack, but in Teamcity it gets stuck in the stopping state. To solve the issue we disable the cloud profile by selecting the terminate running instances option and then reenable it.

As a workaround we are not using the `Terminate instance idle time` option anymore and manually refreshing agents during off-peak hours. But this is blocking us from being dynamic. It would be really great if someone can help us understand the problem and possibly find a solution.

### Further reference
```
Total number of agents we usually spin up ~ 180 (using multiple profiles)
Terminate instance idle time values tried = 15,20,30
OSs = Centos7, Windows 2012, Windows 2016
Teamcity server version: TeamCity Enterprise 2019.1.1 (build 66192)`
```

**Comment by axel3rd** [comment] 2019-09-09 15:12
Hello @redmoses,

> It would be really great if someone can help us understand the problem and possibly find a solution.

In this case, perhaps the [terminate](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/master/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java#L171) call seems ok, but not the last [updateStatus](https://github.com/yandex-qatools/teamcity-openstack-plugin/blob/master/cloud-openstack-server/src/main/java/jetbrains/buildServer/clouds/openstack/OpenstackCloudInstance.java#L63).

> From our investigations we think that this problem occurs mostly when Teamcity is trying to stop multiple agents which reached idle time limit.

Some questions:
1. If you define a cloud profile with `Instance Cap:` to **1**, is the behavior correct (no stopping stuck when *idle time* is reached) ?  *--> To verify if root cause can comes from // run or corner case*
1. Is this bug was existing with TeamCity 2018.x or not (If your usage context can answer) ? *--> to catch some potential TeamCity API/behavior changes*
1. In your `http://teamcity.company.com/admin/admin.html?item=diagnostics&tab=logs`, is there some relevant log in **teamcity-clouds.log** ?
e.g. some error message or exception after this kind of log (instance termination):
```
Will stop instance jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@112233ab, profile 'SomeOpenstackProfile'{id=NOVA-X, projectId=_Root} with idle time X minutes (idle time is X minutes)
Terminating instance: jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@112233ab, profile 'SomeOpenstackProfile'{id=NOVA-X, projectId=_Root}, reason: "Idle timeout reached"
Cloud instance entered 'stopping' state, profile 'SomeOpenstackProfile'{id=NOVA-X, projectId=_Root}, jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@112233ab
```

**Did you have the capacity to enable debug log ? To have the complete termination process of a stopping-stuck instance ?**

Best regards

**Comment by axel3rd** [comment] 2019-09-10 13:19
Problem reproduced with TeamCity v2018.2.4 and ~10 agents => This is a pure plugin bug.

**Comment by axel3rd** [comment] 2019-09-10 13:33
> From our investigations we think that this problem occurs mostly when Teamcity is trying to stop multiple agents which reached idle time limit.

Seems confirmed, with this 3 stop in same time:
```
[2019-09-10 10:23:32,291]   INFO [uled executor 4] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopping' state, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}, jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@62a43d96
[2019-09-10 10:23:32,291]   INFO [uled executor 4] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopping' state, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}, jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@559c782b
[2019-09-10 10:23:32,291]   INFO [uled executor 4] - .server.impl.CloudEventsLogger - Cloud instance entered 'stopping' state, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}, jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@6b812201
[2019-09-10 10:25:00,290]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent "CLOUD_Ubuntu_18.04-1568101875066" {id=12178} because: Instance has been terminated. jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@62a43d96, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}
[2019-09-10 10:25:00,349]   INFO [Ping Executor 1] - .server.impl.CloudEventsLogger - Cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875066" {id=12178} is no longer recognized as cloud agent because instance has gone: profileId=NOVA-X, imageId=1566819391850, instanceId=1568101875066
[2019-09-10 10:25:00,350]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875066" {id=12178} because: Cloud instance (id=1568101875066, imageId=1566819391850, profileId=NOVA-X) has gone (is not reported by cloud profile)
[2019-09-10 10:25:00,357]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent "CLOUD_Ubuntu_18.04-1568101875089" {id=12179} because: Instance has been terminated. jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@559c782b, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}
[2019-09-10 10:25:00,414]   INFO [Ping Executor 1] - .server.impl.CloudEventsLogger - Cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875089" {id=12179} is no longer recognized as cloud agent because instance has gone: profileId=NOVA-X, imageId=1566819391850, instanceId=1568101875089
[2019-09-10 10:25:00,414]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875089" {id=12179} because: Cloud instance (id=1568101875089, imageId=1566819391850, profileId=NOVA-X) has gone (is not reported by cloud profile)
[2019-09-10 10:25:20,792]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent "CLOUD_Ubuntu_18.04-1568101875094" {id=12180} because: Instance has been terminated. jetbrains.buildServer.clouds.openstack.OpenstackCloudInstance@6b812201, profile 'Openstack Profile'{id=NOVA-X, projectId=_Root}
[2019-09-10 10:25:20,876]   INFO [Ping Executor 1] - .server.impl.CloudEventsLogger - Cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875094" {id=12180} is no longer recognized as cloud agent because instance has gone: profileId=NOVA-X, imageId=1566819391850, instanceId=1568101875094
[2019-09-10 10:25:20,876]   INFO [Ping Executor 1] - ces.terminate.AgentRemoverImpl - Removing cloud agent Unregistered agent "CLOUD_Ubuntu_18.04-1568101875094" {id=12180} because: Cloud instance (id=1568101875094, imageId=1566819391850, profileId=NOVA-X) has gone (is not reported by cloud profile)
```

But *AgentRemoverImpl* seems remove correctly the link 😢

**Comment by axel3rd** [comment] 2019-09-10 16:01
Creating 10 agents in // at same time via script (`profileId` & `imageId` can be tracked in browser debug network when agent started via UI, button *start*):

```
#!/bin/sh

for N in `seq 1 10`; do
        echo "--- $N";
        curl -X POST -d "action=startInstance&profileId=NOVA-X&imageId=1234567890" "http://admin:password@teamcity.company.com/clouds/tab.html" &
done
```

I can't reproduce the problem on TeamCity 2019.1.3 ...

**Comment by guillaumelfv** [comment] 2019-09-17 09:28
**1. If you define a cloud profile with Instance Cap: to 1, is the behavior correct (no stopping stuck when idle time is reached) ? --> To verify if root cause can comes from // run or corner case**

Everything work fine when the cloud profile is cap to 1 instances.

**2. Is this bug was existing with TeamCity 2018.x or not (If your usage context can answer) ? --> to catch some potential TeamCity API/behavior changes**

The bug existed in 2018.x.x and we updated Teamcity to the lastest version 2019.1.3 few days ago. As you could not reproduce the issue with this version we hoped it would solve our issue, but unfortunately the issue is still present.

**3. In your http://teamcity.company.com/admin/admin.html?item=diagnostics&tab=logs, is there some relevant log in teamcity-clouds.log ?
e.g. some error message or exception after this kind of log (instance termination)**

We enabled debug mode for the teamcity-cloud logs but we could not see any error, everything seems fine from the logs...

### Here is the latest tests we ran on a test env Teamcity 2019.1.3:

```
- Cloud profile with 15 agents caps and idle time limit of 5mn
- Spawn 15 agents
- We continuously run a bunch of simple builds that can be sustained by 9 agents
```

**1. At some point 6 agents reach the time limit and get stuck in stopped state**

The logs does not show anything unusual:
[teamcity-cloud.log](https://github.com/yandex-qatools/teamcity-openstack-plugin/files/3620294/teamcity-cloud.log)

**2. After one or more agents are stuck in . this specific cloud profile, any stop agents action will failed and get stucked for this cloud profile**

We disabled one agent of the cloud profile to let him reach idle timeout limit and it get stuck (this time we are sure it is the only agents reaching the time limit at this point so no parallel stops). Again nothing unusual in the logs:
[teamcity-cloud-disabledAgent.log](https://github.com/yandex-qatools/teamcity-openstack-plugin/files/3620328/teamcity-cloud-disabledAgent.log)
Same result if clicking the stop UI button for a specific agent:
[teamcity-cloudManualStop.log](https://github.com/yandex-qatools/teamcity-openstack-plugin/files/3620354/teamcity-cloudManualStop.log)

**3. In parallel of all of this another cloud profile with only 1 instance cap and a 5 minutes idle time limit is working fine**
It can be manually stopped with the UI stop button or automatically when reaching the idle time limit.

**Comment by axel3rd** [comment] 2019-09-20 09:07
Thanks @guillaumelfv for this report.

After logs check and mainly *teamcity-cloud-disabledAgent.log*, I can't found relevant root cause of problem in plugin code 😢.
This logs explicits the fact the agent is correctly terminated ; but TeamCity UI is continuing to display in stopping status ...

**Comment by guillaumelfv** [comment] 2019-09-20 14:52
@axel3rd were you able to reproduce the issue yourself in 2019.1.3 with the same scenario we run ?

**Comment by axel3rd** [comment] 2019-09-20 15:05
> @axel3rd were you able to reproduce the issue yourself in 2019.1.3 with the same scenario we run ?

I do not have reproduce the problem on our development platform since we upgrade to 2019.1.3 😕.  (Tried ~20 times to start more 10 agents at same time ...).

Did you have a 100% reproducible scenario where one (or more) agents get in stuck ? (Re-reading you, it is not explicit for me ... can come from my unfluent english)

**Comment by didieraupest** [comment] 2019-10-12 22:51
Can it be related to the JRE version ? Should we use something like openjdk 11, or the old JRE 1.8.x should be fine ?

**Comment by guillaumelfv** [comment] 2019-10-13 04:14
@didieraupest What external database do you use for your Teamcity setup ?
@axel3rd same question, for testing this bug what external database were you using ?

After reading the above message I wonder if it does come from the database / call to database to remove the agent from teamcity or even the DB driver ? Just trhwing out guess/idea here but no proof.

Here what we use:
**database:** external MSSQL
**driver:** sqljdbc72.jar
**java version:** openjdk version "1.8.0_212" / OpenJDK Runtime Environment (build 1.8.0_212-b04)

> the only workaround we found was to desactivate / reactivate all the cloud profiles every day

We also implemented the same workaround for now, by setting no idle timeout and reloading every day.

**Comment by didieraupest** [comment] 2019-10-13 08:57
In our case, the database was PostgreSQL. (9.6 and 11.)

**Comment by axel3rd** [comment] 2019-10-14 08:27
For my part: 
- **java**: Java Oracle 1.8.0_212 
- **database**: Oracle  11.2.0.3.0 

I have reproduce the bug just once ... not on a DEV or local environment, and not since 2019.x version.
=> Hard to investigate from my side.

----

Perhaps the root cause come from that the plugin doesn't "stop" the instance, it "terminates" it directly.
So the "stopping" status doesn't exist really ... and perhaps it disturbs the cloud controller in some corner cases.

**Comment by axel3rd** [comment] 2019-10-30 11:10
> Perhaps the root cause come from that the plugin doesn't "stop" the instance, it "terminates" it directly.
> So the "stopping" status doesn't exist really ... and perhaps it disturbs the cloud controller in some corner cases.

This feature is implemented in [stopping-before-terminate](https://github.com/yandex-qatools/teamcity-openstack-plugin/tree/stopping-before-terminate) branch. PR #41.

1.1-SNAPSHOT build is available: **[cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildSnapshotIntegration/2611207:id/cloud-openstack.zip)**.

Can't reproduce the bug from my side, some tests are mandatory to validate that problem is fixed.
Feature will be rebased/merged for a 1.1 version only after end-user feedbacks (@redmoses  / @guillaumelfv / @guillaumelfv : Need your help 👷).

**Comment by redmoses** [comment] 2019-10-30 11:22
Thanks a lot @axel3rd we will give it a shot and get back to you 😊

**Comment by axel3rd** [comment] 2019-10-30 14:17
> 1.1-SNAPSHOT build is available: cloud-openstack.zip.

This link has been removed, new link: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildBranchesSnapshotIntegration/2611748:id/cloud-openstack.zip).

**Reason**: To improve feature branches build and let the `.lastSuccessful` link on `master`, a dedicated TeamCity [Build branches (SNAPSHOT integration)](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityThirdPartyPlugins_OpenStackCloudSupport_BuildBranchesSnapshotIntegration&branch_TeamCityThirdPartyPlugins_OpenStackCloudSupport=stopping-before-terminate&tab=buildTypeStatusDiv) has been created.

**Comment by didieraupest** [comment] 2019-11-02 11:03
So far, it works perfectly. 
We ddin't had a lot of activity since the update, but it seems to be fine ! 

Thank you for this update !

**Comment by axel3rd** [comment] 2019-11-04 09:19
Thanks for feedback. A v1.1 including this fix will be provided soon.

**Closed** 2019-11-04 09:39 UTC
Labels: bug

**Comment by axel3rd** [comment] 2019-11-06 10:31
Release **v1.1** done. Direct link: [cloud-openstack.zip](https://teamcity.jetbrains.com/repository/download/TeamCityThirdPartyPlugins_OpenStackCloudSupport_Release/2619729:id/cloud-openstack.zip).
